version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: reptionary
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reptionary_production
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server -b 'ssl://0.0.0.0:3000?key=/app/localhost.key&cert=/app/localhost.crt'
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_PASSWORD: password
      DB_NAME: reptionary_production
      DB_USERNAME: reptionary
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: